import commute_img from '../assets/commute_img.png'
import events_img from '../assets/events_img.png'
import analysis_img from '../assets/analysis_img.png'

import map_img from '../assets/map_img.png'
import choose_pin_img from '../assets/choose_pin_img.png'
import toggle_img from '../assets/toggle_img.png'
import join_img from '../assets/join_img.png'
import organize_img from '../assets/organize_img.png'
import dashboard_img from '../assets/dashboard_img.png'
import badge_img from '../assets/badge_img.png'

export const fr = {
  // Translation generated by Google Gemini 3.0 Flash

  userGuide: {
    pageTitle: 'Bien démarrer',
    pageDescription:
      'Votre guide pour des trajets durables et une communauté connectée.',
    miniNav: {
      commute: 'Trajets',
      events: 'Événements',
      impact: 'Impact',
    },
    commuting: {
      image: commute_img,
      title: 'Voyager ensemble',
      subtitle: 'Coordonnez des trajets durables',
      points: [
        {
          term: 'Naviguer sur la carte',
          desc: 'Définissez votre destination en toute simplicité. Utilisez la barre de recherche pour une adresse précise ou déplacez la carte pour épingler le lieu de votre choix.',
          image: map_img,
        },
        {
          term: 'Choisir votre vue',
          desc: 'Basculez entre les vues « Arrivées » et « Départs ». Utilisez « Départs » pour voir les trajets quittant votre zone, ou « Arrivées » pour trouver les itinéraires et événements convergeant vers votre destination.',
          image: toggle_img,
        },
      ],
    },
    events: {
      image: events_img,
      title: 'Événements et itinéraires',
      subtitle: 'Découvrez ce qui se passe autour de vous',
      points: [
        {
          term: 'Explorer les épingles',
          desc: "Appuyez sur n'importe quelle épingle sur la carte pour révéler une liste d'événements et d'itinéraires de transport actifs convergeant vers ce lieu.",
          image: choose_pin_img,
        },
        {
          term: 'Choisir votre itinéraire',
          desc: "Sélectionnez un événement pour voir toutes les options de transport disponibles. Appuyez simplement sur l'itinéraire qui correspond le mieux à votre emploi du temps pour rejoindre le groupe !",
          image: join_img,
        },
        {
          term: 'Prendre les devants',
          desc: "Vous ne trouvez pas d'itinéraire qui vous convient ? Prenez l'initiative et coordonnez un nouveau trajet pour aider les autres à se rendre à l'événement de manière durable.",
          image: organize_img,
        },
      ],
    },
    analysis: {
      image: analysis_img,
      title: 'Votre empreinte verte',
      subtitle: 'Suivez votre impact personnel',
      points: [
        {
          term: 'Visualiser votre impact',
          desc: 'Consultez votre tableau de bord pour voir vos économies personnelles de CO2 et votre contribution à la protection de l’environnement.',
          image: dashboard_img,
        },
        {
          term: 'Gagner et partager',
          desc: 'Gagnez des badges et partagez votre impact avec vos amis pour inspirer les autres à rejoindre cette aventure durable !',
          image: badge_img,
        },
      ],
    },
  },
}
