ALTER TABLE "event" ADD COLUMN IF NOT EXISTS "reported" INTEGER DEFAULT 0;
ALTER TABLE "route" ADD COLUMN IF NOT EXISTS "reported" INTEGER DEFAULT 0;
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "reported" INTEGER DEFAULT 0;

ALTER TABLE "report" ADD COLUMN IF NOT EXISTS "rejection_reason" VARCHAR(50);
ALTER TABLE "report" ADD COLUMN IF NOT EXISTS "rejection_detail" VARCHAR(100);