ALTER TABLE "route"
ALTER COLUMN path TYPE JSONB USING path::JSONB;

UPDATE "route" SET path = '{"legs":[{"steps":[{"distanceMeters":18,"travelMode":"WALK"},{"distanceMeters":26,"travelMode":"WALK"},{"distanceMeters":194,"travelMode":"WALK"},{"distanceMeters":50,"travelMode":"WALK"},{"distanceMeters":4067,"transitDetails":{"stopDetails":{"arrivalStop":{"name":"NB Granville St @ Dunsmuir St","location":{"latLng":{"latitude":49.2834315,"longitude":-123.11658589999999}}},"arrivalTime":"2026-03-04T05:12:56Z","departureStop":{"name":"EB W 4th Ave @ Yew St","location":{"latLng":{"latitude":49.26811,"longitude":-123.15446999999999}}},"departureTime":"2026-03-04T04:58:08Z"},"localizedValues":{"arrivalTime":{"time":{"text":"9:12 PM"},"timeZone":"America/Vancouver"},"departureTime":{"time":{"text":"8:58 PM"},"timeZone":"America/Vancouver"}},"headsign":"Nanaimo Station","transitLine":{"agencies":[{"name":"TransLink","phoneNumber":"+1 604-953-3333","uri":"https://www.translink.ca/"}],"name":"Nanaimo Station/Dunbar","nameShort":"007","vehicle":{"name":{"text":"Bus"},"type":"BUS","iconUri":"//maps.gstatic.com/mapfiles/transit/iw2/6/bus2.png"}},"stopCount":9},"travelMode":"TRANSIT"},{"distanceMeters":22,"travelMode":"WALK"},{"distanceMeters":103,"travelMode":"WALK"},{"distanceMeters":64,"travelMode":"WALK"}]}],"distanceMeters":4544,"polyline":{"encodedPolyline":"kiukHpytnVo@@@y@@WATuHI@i@@uBI?I?Vkq@HuQ?mAJiAFwQL_LLcARs@Zm@NEHIfAaBz@UKfLMh@wFK_AMwAa@s@]s@g@y@kAiOiWqBiDsEgIWSyKuRYS_E}GWm@iLyRmBiDEKgSm]q@gAHOA@S_@BES]fBcDcAiB"}}' WHERE id = 1;
UPDATE "route" SET path = '{"legs":[{"steps":[{"distanceMeters":14,"travelMode":"WALK"},{"distanceMeters":479,"travelMode":"WALK"},{"distanceMeters":75,"travelMode":"WALK"},{"distanceMeters":5881,"transitDetails":{"stopDetails":{"arrivalStop":{"name":"WB W Pender St @ Seymour St","location":{"latLng":{"latitude":49.283785099999996,"longitude":-123.11342339999999}}},"arrivalTime":"2026-03-04T05:18:26Z","departureStop":{"name":"NB Knight St @ E 20 Ave","location":{"latLng":{"latitude":49.252354,"longitude":-123.075894}}},"departureTime":"2026-03-04T04:57:28Z"},"localizedValues":{"arrivalTime":{"time":{"text":"9:18 PM"},"timeZone":"America/Vancouver"},"departureTime":{"time":{"text":"8:57 PM"},"timeZone":"America/Vancouver"}},"headsign":"Downtown","transitLine":{"agencies":[{"name":"TransLink","phoneNumber":"+1 604-953-3333","uri":"https://www.translink.ca/"}],"name":"Knight/Downtown","nameShort":"022","vehicle":{"name":{"text":"Bus"},"type":"BUS","iconUri":"//maps.gstatic.com/mapfiles/transit/iw2/6/bus2.png"}},"stopCount":22},"travelMode":"TRANSIT"},{"distanceMeters":41,"travelMode":"WALK"},{"distanceMeters":100,"travelMode":"WALK"}]}],"distanceMeters":6590,"polyline":{"encodedPolyline":"cnrkHf~cnVL?A`DGTEtIBPE`KEpCCvFqAGa@??A?JkLIyIMkAC{@D{@Vc@`@[d@_@`Aa@fAk@t@g@Zg@HaB?_FEsGHuMMi@RcWUmA?eBImGCqBC_@J}GK_[MK~b@JtAh@vCJrAElOa@xu@Cz@OhBaDX_BDmGb@uDd@Yji@OtBWlBMfByClX[~@uAbCmIdOEGCE_AbBR\\v@rA|@xA"}}' WHERE id = 2;
UPDATE "route" SET path = '{"legs":[{"steps":[{"distanceMeters":24,"travelMode":"WALK"},{"distanceMeters":24,"travelMode":"WALK"},{"distanceMeters":103,"travelMode":"WALK"},{"distanceMeters":3022,"transitDetails":{"stopDetails":{"arrivalStop":{"name":"Main Street-Science World","location":{"latLng":{"latitude":49.273137899999995,"longitude":-123.1004569}}},"arrivalTime":"2026-03-04T05:00:00Z","departureStop":{"name":"Waterfront","location":{"latLng":{"latitude":49.286189099999994,"longitude":-123.11188659999999}}},"departureTime":"2026-03-04T04:54:00Z"},"localizedValues":{"arrivalTime":{"time":{"text":"9:00 PM"},"timeZone":"America/Vancouver"},"departureTime":{"time":{"text":"8:54 PM"},"timeZone":"America/Vancouver"}},"headsign":"King George","transitLine":{"agencies":[{"name":"TransLink","phoneNumber":"+1 604-953-3333","uri":"https://www.translink.ca/"}],"name":"Expo Line","color":"#0033a0","textColor":"#ffffff","vehicle":{"name":{"text":"Subway"},"type":"SUBWAY","iconUri":"//maps.gstatic.com/mapfiles/transit/iw2/6/subway2.png"}},"stopCount":5},"travelMode":"TRANSIT"},{"distanceMeters":30,"travelMode":"WALK"},{"distanceMeters":70,"travelMode":"WALK"},{"distanceMeters":7,"travelMode":"WALK"},{"distanceMeters":209,"travelMode":"WALK"}]}],"distanceMeters":3489,"polyline":{"encodedPolyline":"oaykH~clnVTw@\\n@OXiDvB@hA}BnHaD~LO`AiA`LC`AHbBNbAZ`AP^f@n@l@b@j@Pp@Dx@Kj@[j@i@nAuBt_@sq@Vs@Ny@J}@Tw@~@eBZ[|AiCpD}GP[d@}AZeBD[h@iKPoAVeATk@b@u@n@s@z@g@jAW|Fg@jE[b@KXO^i@Ti@Nu@Z{DEA?rAL@M~B@??`@D@?r@E?@vCDNET@vBN`@Db@Cd@MVYXQDK?"}}' WHERE id = 3;
UPDATE "route" SET path = '{"legs":[{"steps":[{"distanceMeters":84,"travelMode":"WALK"},{"distanceMeters":162,"travelMode":"WALK"},{"distanceMeters":68,"travelMode":"WALK"},{"distanceMeters":15,"travelMode":"WALK"},{"distanceMeters":82,"travelMode":"WALK"},{"distanceMeters":10943,"transitDetails":{"stopDetails":{"arrivalStop":{"name":"Granville","location":{"latLng":{"latitude":49.2831009,"longitude":-123.11580230000001}}},"arrivalTime":"2026-03-04T05:11:00Z","departureStop":{"name":"Metrotown","location":{"latLng":{"latitude":49.2259362,"longitude":-123.00402749999999}}},"departureTime":"2026-03-04T04:54:00Z"},"localizedValues":{"arrivalTime":{"time":{"text":"9:11 PM"},"timeZone":"America/Vancouver"},"departureTime":{"time":{"text":"8:54 PM"},"timeZone":"America/Vancouver"}},"headsign":"Waterfront","transitLine":{"agencies":[{"name":"TransLink","phoneNumber":"+1 604-953-3333","uri":"https://www.translink.ca/"}],"name":"Expo Line","color":"#0033a0","textColor":"#ffffff","vehicle":{"name":{"text":"Subway"},"type":"SUBWAY","iconUri":"//maps.gstatic.com/mapfiles/transit/iw2/6/subway2.png"}},"stopCount":9},"travelMode":"TRANSIT"},{"distanceMeters":28,"travelMode":"WALK"},{"distanceMeters":148,"travelMode":"WALK"},{"distanceMeters":228,"travelMode":"WALK"},{"distanceMeters":18,"travelMode":"WALK"},{"distanceMeters":71,"travelMode":"WALK"},{"distanceMeters":25,"travelMode":"WALK"}]}],"distanceMeters":11872,"polyline":{"encodedPolyline":"owmkHfbwmVENOz@s@fB`BjBXTbBfBRZHFHMr@cCJLlA_EHHcInU}H`UkC`IuEzLiB~EaEnLoDrKaE~M{FnPq@nAWt@YjAcAxCgBnEmArC}AlEmHdVcHlUaLd^aEhN_CpH{@fCsCjJsAbEiEjNkB~FoDdLsMnb@}D|Lk@jBeApCaBnCsHtKw@dAsApAiAt@w@b@yA^oALyT?iFJaICu@Bm@Ls@^ON[l@Sj@sA|FwClNiGvXm@fBw@zAwA`BeFnD}@v@i@n@i@v@{@lBa@rASbAyChTyIh_Ac@tE]lBQp@MVm@zBW`B_AhKUfBK^Sb@_@^YL}BVyJz@}@Xu@f@o@r@s@xA_@`BSzBa@jHUbBc@bBYr@{GzLOf@_AdBUv@SzASt@KXyO~XJRc@v@AEcAlBACa@r@M`@qAvBj@`ARRjCrEZn@r@lAINxAhC_@r@"}}' WHERE id = 4;

-- uncomment this if you have run db init too many times:

-- DELETE FROM "route" WHERE id > 4;
-- DELETE FROM "event" WHERE id > 3;
-- DELETE FROM "vehicle" WHERE id > 3;
-- DELETE FROM "badge" WHERE id > 4;